default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>

development:
  <<: *default
  port: 5432
  database: random_room_allocator_development

test:
  <<: *default
  port: 5432
  database: random_room_allocator_test
# staging:
#   <<: *default

# production:
#   <<: *default
