#!/usr/bin/env ruby

# require 'bundler/setup'
require 'dotenv'

Dotenv.load

$LOAD_PATH.unshift File.expand_path('..', __dir__)

require 'config/application'

Runner.start ENV['ENVIRONMENT']
